---
title: "cours_r_partie_3"
---

```{r}
library(readr)
library(tidyverse)
df_velos <- read_delim("data/velos.csv", delim = ";")
```

# 2. 
```{r}
df_b_788 <- df_velos[df_velos$`Numéro de boucle`==788,]
df_b_677 <- df_velos[df_velos$`Numéro de boucle`==677,]

df_d_1110 <- df_velos[df_velos$Jour=="2025-10-11",]
df_d_1113 <- df_velos[df_velos$Jour=="2025-10-13",]
df_b_677$`Probabilité de présence d'anomalies`

```

# 3. 

```{r}
filtre_anomalie <- function(df_entree){
  liste <- c("Forte", "Faible")
  
  df_propre <- df_entree[ !(df_entree$`Probabilité de présence d'anomalies` %in% liste), ]
  return(df_propre)
}

df_b_677_p <- filtre_anomalie(df_b_677)
df_b_788_p <- filtre_anomalie(df_b_788)

df_d_1110_p <- filtre_anomalie(df_d_1110)
df_d_1113_p <- filtre_anomalie(df_d_1113)

```

# 4.

```{r}
compter_nombre_trajets <- function(df_entree){
  nb_trajets <- sum(df_entree$Total)
  return(nb_trajets)
}
compter_nombre_trajets(df_b_677_p)
compter_nombre_trajets(df_b_788_p)
compter_nombre_trajets(df_d_1110_p)
compter_nombre_trajets(df_d_1113_p)

```

# 5.

```{r}
compter_nombre_boucle <- function(df_entree){
  nb_boucle <- df_entree |> 
    distinct(`Numéro de boucle`) |> 
    nrow()
  return(nb_boucle)
}
compter_nombre_boucle(df_b_677_p)
compter_nombre_boucle(df_b_788_p)
compter_nombre_boucle(df_d_1110_p)
compter_nombre_boucle(df_d_1113_p)
```

# 6.

```{r}
trouver_trajet_max <- function(df_entree){
  max_total <- which.max(df_entree$Total)
  
  nom_boucle <- df_entree$`Boucle de comptage`[max_total]
  jour_max <- df_entree$Jour[max_total]
  valeur_max <- df_entree$Total[max_total]
  
  liste <- list(
    nom = nom_boucle,
    jour = jour_max,
    valeur = valeur_max
  )
  return(liste)
}
trouver_trajet_max(df_b_677_p)
trouver_trajet_max(df_b_788_p)
trouver_trajet_max(df_d_1110_p)
trouver_trajet_max(df_d_1113_p)
```

# 7.

```{r}
trouver_trajet_max(df_velos)
```
Les valeurs sont aberrantes et ne correspondent pas à la réalité. Il y a un problème dans le jeu de donnée sur certaines lignes.
```{r}
df_velos_trie <- df_velos |> 
  arrange(desc(Total))
df_velos_trie$Total

filtre_anomalie_2 <- function(df_entree){
  liste <- c("Forte", "Faible")
  df_propre <- df_entree[ !(df_entree$`Probabilité de présence d'anomalies` %in% liste), ]
  df_propre <- subset(df_entree, Total < 10000)
  return(df_propre)
}

df_b_677_f <- filtre_anomalie_2(df_b_677)
df_b_788_f <- filtre_anomalie_2(df_b_788)
df_d_1110_f <- filtre_anomalie_2(df_d_1110)
df_d_1113_f <- filtre_anomalie_2(df_d_1113)
df_velos_f <- filtre_anomalie_2(df_velos)

trouver_trajet_max(df_velos_f)
```

# 8.

```{r}
calcul_distribution_semaine <- function(df_entree) {
  df_propre <- df_entree |> 
    group_by(`Jour de la semaine`) |> 
    summarise(Total_Jour = sum(Total, na.rm = TRUE)) |> 
    arrange(Total_Jour)
  
  return(df_propre)
}
calcul_distribution_semaine(df_velos_f)
```


